name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unix-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version:
          - 27.1
          - 27.2
          - snapshot

    steps:
      - uses: actions/checkout@v2

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - uses: conao3/setup-cask@master
        with:
          version: 0.8.4

      - name: Run tests
        run: 'make ci'

  windows-test:
    runs-on: windows-latest
    strategy:
      matrix:
        emacs-version:
          - 27.1
          - 27.2
          - snapshot

    steps:
      - uses: actions/checkout@v2

      - uses: jcs090218/setup-emacs-windows@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - uses: conao3/setup-cask@master
        with:
          version: 0.8.4

      - name: Run tests
        run: 'make ci'
